// Auto-generated — 36 mini games from 我的暑假计划.html (5 min / session)
const BA_GAME_SEC = 300;
let baGTm=null,baGScr=0,baGDur=0,baGInt=null,baGData={},baGCv=null,baGCtx=null,baGRaf=null,baGAct=false;
const BA_GAMES=[];

function baGameEnd(sc){
  baGAct=false;
  clearInterval(baGInt);
  clearTimeout(baGTm);
  if(baGRaf) cancelAnimationFrame(baGRaf);
  if(typeof onBaGameSessionEnd==="function") onBaGameSessionEnd(sc, Math.floor(sc/10));
}

function gT2(sec){ baGDur=sec; baGInt=setInterval(function(){
  baGDur--;
  var el=document.getElementById("ba-g-score");
  if(el) el.textContent="⏱"+baGDur+"s|"+baGScr;
  if(baGDur<=0) baGameEnd(baGScr);
},1000); }

function gEnd(sc){ baGameEnd(sc); }



function gCC(cf){const a=document.getElementById('ba-g-area');a.style.cssText='min-height:240px;position:relative;overflow:hidden;background:#fafaf9;touch-action:manipulation';a.innerHTML='';baGScr=0;baGAct=true;gT2(cf.t||600);function spwn(){if(!baGAct)return;const el=document.createElement('div');el.style.cssText='position:absolute;width:'+(cf.sz||50)+'px;height:'+(cf.sz||50)+'px;border-radius:50%;background:'+(cf.bg||'#f66')+';display:flex;align-items:center;justify-content:center;font-size:'+(cf.fs||24)+'px;cursor:pointer;left:'+Math.random()*85+'%;top:'+Math.random()*75+'%;z-index:1';el.textContent=cf.ic||'🎯';el.addEventListener('pointerdown',function(e){e.preventDefault();if(!baGAct)return;if(cf.bm&&el.dataset.bm){baGScr=Math.max(0,baGScr-5);el.remove();return}baGScr+=cf.pt||1;el.style.transform='scale(1.5)';el.style.opacity='0';setTimeout(()=>el.remove(),150);document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr});a.appendChild(el);if(cf.bm)el.dataset.bm='1';setTimeout(()=>{if(el.parentNode)el.remove()},cf.lf||1500)}spwn();cf.spw=setInterval(spwn,cf.sp||800);baGData.cl=()=>{clearInterval(cf.spw);while(a.firstChild)a.removeChild(a.firstChild)}}
function baGCvC(cf){const a=document.getElementById('ba-g-area');a.innerHTML='<canvas id="baGCv3" style="width:100%;height:240px;display:block;touch-action:none"></canvas>';const cv=document.getElementById('baGCv3');cv.width=cv.offsetWidth*2;cv.height=480;baGCv=cv;baGCtx=cv.getContext('2d');baGScr=0;baGAct=true;gT2(cf.t||600);baGData={};cf.ini(baGCtx,cv.width,cv.height,baGData);function lp(){if(!baGAct){if(cf.cl2)cf.cl2(baGData);return}baGCtx.clearRect(0,0,cv.width,cv.height);cf.upd(baGCtx,cv.width,cv.height,baGData,baGScr);baGRaf=requestAnimationFrame(lp)}lp();cv.addEventListener('pointerdown',function(e){if(!baGAct)return;const r=cv.getBoundingClientRect();if(cf.clk)cf.clk((e.clientX-r.left)*2,(e.clientY-r.top)*2,baGData)});cv.addEventListener('pointermove',function(e){if(!baGAct||!cf.mv)return;const r=cv.getBoundingClientRect();baGData.mx=(e.clientX-r.left)*2;baGData.my=(e.clientY-r.top)*2});a._cl2=()=>{baGAct=false;if(cf.cl2)cf.cl2(baGData)};baGData.inc=n=>{baGScr+=n;document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr}}



// 1-12: Reaction
BA_GAMES.push({id:1,n:'打地鼠',ic:'🔨',cat:'反应',t:BA_GAME_SEC,ini2:()=>gCC({ic:'🐹',sz:55,fs:30,bg:'#8B4513',pt:1,sp:700,lf:1200})});BA_GAMES.push({id:2,n:'戳气球',ic:'🎈',cat:'反应',t:BA_GAME_SEC,ini2:()=>gCC({ic:'🎈',sz:45,fs:28,bg:'#f66',pt:1,sp:500,lf:2000})});BA_GAMES.push({id:3,n:'拍苍蝇',ic:'🪰',cat:'反应',t:BA_GAME_SEC,ini2:()=>gCC({ic:'🪰',sz:35,fs:22,bg:'#333',pt:1,sp:400,lf:1000})});
BA_GAMES.push({id:4,n:'接水果',ic:'🍎',cat:'反应',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:280px;position:relative;overflow:hidden;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);let bs=document.createElement('div');bs.style.cssText='position:absolute;bottom:10px;width:80px;height:20px;background:#8B4513;border-radius:10px;left:50%;transform:translateX(-50%);z-index:5;transition:left .1s';a.appendChild(bs);a.addEventListener('pointermove',function(e){const r=a.getBoundingClientRect();bs.style.left=Math.max(0,Math.min(r.width-80,e.clientX-r.left-40))+'px'});a.addEventListener('touchmove',function(e){const r=a.getBoundingClientRect();bs.style.left=Math.max(0,Math.min(r.width-80,e.touches[0].clientX-r.left-40))+'px'},{passive:true});baGData.sp=setInterval(()=>{if(!baGAct)return;const f=document.createElement('div');f.style.cssText='position:absolute;width:30px;height:30px;border-radius:50%;top:-30px;left:'+Math.random()*90+'%;font-size:24px;text-align:center;line-height:30px;z-index:2';f.textContent=['🍎','🍊','🍋','🍇','🍓','⭐'][Math.floor(Math.random()*6)];let fy=-30;function dp(){if(!baGAct||!f.parentNode)return;fy+=3;f.style.top=fy+'px';if(fy>270&&fy<290){const fx=parseInt(f.style.left)/100*a.offsetWidth,bx=parseInt(bs.style.left)||0;if(fx>bx-20&&fx<bx+80){baGScr+=f.textContent==='⭐'?3:1;document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr;f.remove();return}}if(fy>320){f.remove();return}requestAnimationFrame(dp)}a.appendChild(f);requestAnimationFrame(dp)},800);baGData.cl=()=>{clearInterval(baGData.sp);while(a.firstChild)a.removeChild(a.firstChild)}}});
BA_GAMES.push({id:5,n:'反应测试',ic:'⚡',cat:'反应',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;align-items:center;justify-content:center;background:#fafaf9;cursor:pointer';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);function rd(){if(!baGAct)return;a.style.background='#e34948';a.innerHTML='<div style="font-size:44px">🔴</div><div style="font-size:13px;color:#fff">等待绿色...</div>';baGData.tm=setTimeout(()=>{if(!baGAct)return;a.style.background='#0ca30c';a.innerHTML='<div style="font-size:44px">🟢</div><div style="font-size:13px;color:#fff">快点击！</div>';baGData.st=Date.now();baGData.rdy=true},800+Math.random()*2000)}baGData.rdy=false;rd();a.addEventListener('pointerdown',function(){if(!baGAct)return;if(baGData.rdy){baGScr+=Math.max(1,Math.floor((1000-(Date.now()-baGData.st))/100));document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr;baGData.rdy=false;a.style.background='#fafaf9';clearTimeout(baGData.tm);setTimeout(rd,500)}});baGData.cl=()=>{clearTimeout(baGData.tm)}}});
BA_GAMES.push({id:6,n:'快速点击',ic:'👆',cat:'反应',t:BA_GAME_SEC,ini2:()=>gCC({ic:'🎯',sz:45,fs:28,bg:'#2a78d6',pt:1,sp:350,lf:900})});BA_GAMES.push({id:7,n:'星星收集',ic:'⭐',cat:'反应',t:BA_GAME_SEC,ini2:()=>gCC({ic:'⭐',sz:40,fs:26,bg:'#fd0',pt:3,sp:1000,lf:1800})});BA_GAMES.push({id:8,n:'泡泡消除',ic:'🫧',cat:'反应',t:BA_GAME_SEC,ini2:()=>gCC({ic:'🫧',sz:50,fs:30,bg:'#87CEEB',pt:1,sp:600,lf:2500})});
BA_GAMES.push({id:9,n:'颜色快按',ic:'🎨',cat:'反应',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);const ws2=[{t:'红',c:'#e34948'},{t:'蓝',c:'#2a78d6'},{t:'绿',c:'#0ca30c'},{t:'黄',c:'#eda100'}];const cs2=['#e34948','#2a78d6','#0ca30c','#eda100'];function nw(){if(!baGAct)return;const w2=ws2[Math.floor(Math.random()*4)],c=cs2[Math.floor(Math.random()*4)];a.innerHTML='';const el=document.createElement('div');el.style.cssText='font-size:32px;font-weight:800;color:'+c+';padding:16px 32px;border-radius:14px;background:#fff;box-shadow:0 2px 12px rgba(0,0,0,.1);cursor:pointer;user-select:none';el.textContent=w2.t;const mt=w2.c===c;el.addEventListener('pointerdown',function(){if(!baGAct)return;if(mt){baGScr+=2}else{baGScr=Math.max(0,baGScr-1)}document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr;nw()});a.appendChild(el);const l=document.createElement('div');l.style.cssText='font-size:13px;color:var(--i3)';l.textContent=mt?'字色一致→点击！':'字色不同→别点！';a.appendChild(l)}nw()}});
BA_GAMES.push({id:10,n:'躲避炸弹',ic:'💣',cat:'反应',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;position:relative;overflow:hidden;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);function sp10(){if(!baGAct)return;const bm=Math.random()<.3;const el=document.createElement('div');el.style.cssText='position:absolute;width:48px;height:48px;border-radius:50%;background:'+(bm?'#333':'#ff9500')+';display:flex;align-items:center;justify-content:center;font-size:24px;cursor:pointer;left:'+Math.random()*85+'%;top:'+Math.random()*75+'%;z-index:1';el.textContent=bm?'💣':'⭐';el.addEventListener('pointerdown',function(e){e.preventDefault();if(!baGAct)return;if(bm){baGScr=Math.max(0,baGScr-3)}else{baGScr+=1;document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr}el.remove()});a.appendChild(el);setTimeout(()=>{if(el.parentNode)el.remove()},1200)}sp10();baGData.sp=setInterval(sp10,600);baGData.cl=()=>{clearInterval(baGData.sp);while(a.firstChild)a.removeChild(a.firstChild)}}});
BA_GAMES.push({id:11,n:'套圈圈',ic:'⭕',cat:'反应',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:14px;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);const s2=document.createElement('style');s2.textContent='@keyframes sw{0%,100%{left:50px}50%{left:90px}}';a.appendChild(s2);const wr=document.createElement('div');wr.style.cssText='position:relative;width:200px;height:100px;display:flex;align-items:center;justify-content:center';const pg=document.createElement('div');pg.style.cssText='width:6px;height:70px;background:#8B4513;border-radius:3px';const ri=document.createElement('div');ri.style.cssText='position:absolute;width:56px;height:56px;border:4px solid #ff9500;border-radius:50%;left:70px;top:22px;animation:sw .8s ease-in-out infinite';wr.appendChild(pg);wr.appendChild(ri);a.appendChild(wr);const b2=document.createElement('button');b2.style.cssText='padding:10px 24px;border-radius:18px;border:none;background:#2a78d6;color:#fff;font-size:14px;font-weight:700;cursor:pointer;min-height:42px';b2.textContent='⭕套圈！';b2.addEventListener('pointerdown',function(){if(!baGAct)return;const rl=parseInt(ri.style.left)||70;if(rl>62&&rl<78){baGScr+=3}else{baGScr=Math.max(0,baGScr-1)}document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr;ri.style.animation='none';ri.style.left=(50+Math.random()*40)+'px';setTimeout(()=>{ri.style.animation='sw .8s ease-in-out infinite'},50)});a.appendChild(b2)}});
BA_GAMES.push({id:12,n:'射击靶心',ic:'🎯',cat:'反应',t:BA_GAME_SEC,ini2:()=>gCC({ic:'🎯',sz:55,fs:30,bg:'#e34948',pt:2,sp:900,lf:1400})});
// 13-18: Memory
BA_GAMES.push({id:13,n:'记忆翻牌',ic:'🃏',cat:'记忆',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:280px;display:grid;grid-template-columns:repeat(4,1fr);gap:5px;padding:6px;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);const em=['🍎','🌟','🎈','🐶','🌸','⚡'];const cs3=[...em,...em].sort(()=>Math.random()-.5);let fl=[],mt2=[];cs3.forEach((em2,i)=>{const c=document.createElement('div');c.style.cssText='aspect-ratio:1;background:#2a78d6;border-radius:7px;display:flex;align-items:center;justify-content:center;font-size:26px;cursor:pointer;color:transparent;transition:all .2s';c.textContent=em2;c.addEventListener('pointerdown',function(){if(!baGAct||fl.length>=2||mt2.includes(i)||fl.includes(i))return;c.style.background='#fff';c.style.color='#000';fl.push(i);if(fl.length===2){const[c1,c2]=fl.map(x=>a.children[x]);if(cs3[fl[0]]===cs3[fl[1]]){mt2.push(...fl);baGScr+=5;document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr;setTimeout(()=>{c1.style.opacity='0';c2.style.opacity='0'},300);fl=[];if(mt2.length===12){baGScr+=10;gEnd(baGScr)}}else{setTimeout(()=>{c1.style.background='#2a78d6';c1.style.color='transparent';c2.style.background='#2a78d6';c2.style.color='transparent';fl=[]},600)}}});a.appendChild(c)})}});
BA_GAMES.push({id:14,n:'西蒙说',ic:'🎵',cat:'记忆',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;align-items:center;justify-content:center;gap:8px;background:#fafaf9';baGScr=0;baGAct=true;const cs4=['#e34948','#2a78d6','#0ca30c','#eda100'];let sq=[],pI=0,pP='show';const bs2=cs4.map((c,i)=>{const b=document.createElement('button');b.style.cssText='width:56px;height:56px;border-radius:50%;border:none;background:'+c+';cursor:pointer;margin:3px;opacity:.6;transition:opacity .2s;min-height:56px';b.addEventListener('pointerdown',function(){if(!baGAct||pP!=='input')return;if(i===sq[pI]){pI++;if(pI>=sq.length){baGScr+=sq.length;document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr;sq.push(Math.floor(Math.random()*4));pI=0;setTimeout(pSq,800)}}else{baGScr=Math.max(0,baGScr-1);pI=0;setTimeout(pSq,500)}});return b});a.append(...bs2);gT2(BA_GAME_SEC);function pSq(){if(!baGAct)return;pP='show';let i=0;function fl2(){if(i>=sq.length){pP='input';pI=0;return}bs2[sq[i]].style.opacity='1';setTimeout(()=>{bs2[sq[i]].style.opacity='.6';i++;setTimeout(fl2,200)},400)}fl2()}sq=[Math.floor(Math.random()*4)];setTimeout(pSq,500)}});
BA_GAMES.push({id:15,n:'数字记忆',ic:'🔢',cat:'记忆',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);let nm='',ln=3;function nr(){ln=3+Math.floor(baGScr/5);nm='';for(let i=0;i<ln;i++)nm+=Math.floor(Math.random()*10);a.innerHTML='<div style="font-size:36px;font-weight:800;letter-spacing:8px">'+nm+'</div><div style="font-size:12px;color:var(--i3)">记住（'+ln+'位）</div>';setTimeout(()=>{if(!baGAct)return;a.innerHTML='<input id="ni2" style="font-size:24px;width:180px;padding:8px;text-align:center;border:2px solid #e5e5ea;border-radius:9px;letter-spacing:4px" placeholder="输入"><button class="bs bb" style="margin-top:6px;font-size:13px" onclick="var v=document.getElementById(\'ni2\').value;if(v===\''+nm+'\'){baGScr+=3;document.getElementById(\'ba-g-score\').textContent=\'⏱\'+baGDur+\'s|\'+baGScr}else{baGScr=Math.max(0,baGScr-1)}nr()">确认</button>'},1500+ln*500)}nr()}});
BA_GAMES.push({id:16,n:'颜色顺序',ic:'🌈',cat:'记忆',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);const cs5=['#e34948','#2a78d6','#0ca30c','#eda100','#eb6834','#4a3aa7'];let sq2=[],an=[];function nr2(){const l2=3+Math.floor(baGScr/4);sq2=[];for(let i=0;i<l2;i++)sq2.push(Math.floor(Math.random()*cs5.length));an=[];a.innerHTML='';const cd=document.createElement('div');cd.style.cssText='display:flex;gap:6px';sq2.forEach(c=>{const d=document.createElement('div');d.style.cssText='width:36px;height:36px;border-radius:50%;background:'+cs5[c];cd.appendChild(d)});a.appendChild(cd);a.appendChild(document.createElement('div')).style.cssText='font-size:11px;color:var(--i3);margin-top:3px';a.lastChild.textContent='记住顺序！';setTimeout(()=>{if(!baGAct)return;a.innerHTML='<div style="font-size:12px;margin-bottom:6px">按顺序点击</div>';const rd2=document.createElement('div');rd2.style.cssText='display:flex;gap:5px;flex-wrap:wrap;justify-content:center';const sf=[...sq2].sort(()=>Math.random()-.5);const sn2=[];sf.forEach(c=>{if(sn2.includes(c))return;sn2.push(c);const b=document.createElement('button');b.style.cssText='width:40px;height:40px;border-radius:50%;border:none;background:'+cs5[c]+';cursor:pointer;min-height:40px';b.addEventListener('pointerdown',function(){if(!baGAct)return;an.push(c);if(an[an.length-1]!==sq2[an.length-1]){baGScr=Math.max(0,baGScr-1);an=[];nr2();return}if(an.length===sq2.length){baGScr+=sq2.length;document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr;nr2()}});rd2.appendChild(b)});a.appendChild(rd2)},2000+sq2.length*300)}nr2()}});
BA_GAMES.push({id:17,n:'找不同',ic:'🔍',cat:'记忆',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;flex-wrap:wrap;gap:5px;align-items:center;justify-content:center;padding:10px;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);function nr3(){const e2=['🍎','🍊','🍋','🍇','🍓','🍑','🍒','🥝'];const b2=e2[Math.floor(Math.random()*e2.length)];const d2=e2.filter(e3=>e3!==b2)[Math.floor(Math.random()*7)];const n2=9+Math.floor(Math.random()*7),oi=Math.floor(Math.random()*n2);a.innerHTML='';for(let i=0;i<n2;i++){const d=document.createElement('div');d.style.cssText='font-size:28px;cursor:pointer;padding:3px;min-width:40px;min-height:40px;display:flex;align-items:center;justify-content:center';d.textContent=i===oi?d2:b2;d.addEventListener('pointerdown',function(){if(!baGAct)return;if(i===oi){baGScr+=2}else{baGScr=Math.max(0,baGScr-1)}document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr;nr3()});a.appendChild(d)}}nr3()}});
BA_GAMES.push({id:18,n:'位置记忆',ic:'📍',cat:'记忆',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;position:relative;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);function nr4(){const gs=3,cs6=[];for(let i=0;i<gs*gs;i++)cs6.push(i);const pk=[];for(let i=0;i<3;i++){const ix=Math.floor(Math.random()*cs6.length);pk.push(cs6.splice(ix,1)[0])}a.innerHTML='';a.style.display='grid';a.style.gridTemplateColumns='repeat('+gs+',1fr)';a.style.gap='4px';a.style.padding='10px';for(let i=0;i<gs*gs;i++){const c=document.createElement('div');c.style.cssText='aspect-ratio:1;background:#e5e5ea;border-radius:5px;display:flex;align-items:center;justify-content:center;font-size:20px';if(pk.includes(i))c.textContent='⭐';a.appendChild(c)}setTimeout(()=>{if(!baGAct)return;for(let i=0;i<gs*gs;i++){a.children[i].textContent='';a.children[i].style.cursor='pointer';a.children[i].onclick=function(){if(!baGAct)return;if(pk.includes(i)){baGScr+=2}else{baGScr=Math.max(0,baGScr-1)}document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr;nr4()}}},1500)}nr4()}});
// 19-24: Math
BA_GAMES.push({id:19,n:'速算挑战',ic:'🧮',cat:'数学',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);function nq(){if(!baGAct)return;const ops=['+','-','×'];const op=ops[Math.floor(Math.random()*3)];let a2,b2,an2;if(op==='+'){a2=Math.floor(Math.random()*50)+10;b2=Math.floor(Math.random()*50)+10;an2=a2+b2}else if(op==='-'){a2=Math.floor(Math.random()*50)+30;b2=Math.floor(Math.random()*30)+1;an2=a2-b2}else{a2=Math.floor(Math.random()*9)+2;b2=Math.floor(Math.random()*9)+2;an2=a2*b2}a.innerHTML='<div style="font-size:30px;font-weight:800">'+a2+' '+op+' '+b2+' = ?</div><input id="ma2" style="font-size:22px;width:130px;padding:7px;text-align:center;border:2px solid #e5e5ea;border-radius:9px" placeholder="?"><button class="bs bb" style="font-size:13px;margin-top:5px" onclick="var v=parseInt(document.getElementById(\'ma2\').value);if(v==='+an2+'){baGScr+=2}else{baGScr=Math.max(0,baGScr-1)}document.getElementById(\'ba-g-score\').textContent=\'⏱\'+baGDur+\'s|\'+baGScr;nq()">确认</button>'}nq()}});
BA_GAMES.push({id:20,n:'比大小',ic:'📏',cat:'数学',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:14px;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);function nq2(){if(!baGAct)return;const n1=Math.floor(Math.random()*900)+10,n2=Math.floor(Math.random()*900)+10;a.innerHTML='<div style="font-size:26px;font-weight:800">'+n1+' ? '+n2+'</div><div style="display:flex;gap:10px"><button style="font-size:18px;padding:10px 22px;background:#2a78d6;color:#fff;border:none;border-radius:12px;min-height:44px;cursor:pointer" onclick="if('+n1+'>'+n2+'){baGScr+=1}else{baGScr=Math.max(0,baGScr-1)}nq2()">＞</button><button style="font-size:18px;padding:10px 22px;background:#e34948;color:#fff;border:none;border-radius:12px;min-height:44px;cursor:pointer" onclick="if('+n1+'<'+n2+'){baGScr+=1}else{baGScr=Math.max(0,baGScr-1)}nq2()">＜</button><button style="font-size:18px;padding:10px 22px;background:#0ca30c;color:#fff;border:none;border-radius:12px;min-height:44px;cursor:pointer" onclick="if('+n1+'==='+n2+'){baGScr+=2}else{baGScr=Math.max(0,baGScr-1)}nq2()">＝</button></div>'}nq2()}});
BA_GAMES.push({id:21,n:'九九乘法',ic:'✖️',cat:'数学',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);function nq3(){if(!baGAct)return;const n1=Math.floor(Math.random()*9)+1,n2=Math.floor(Math.random()*9)+1,an3=n1*n2;a.innerHTML='<div style="font-size:30px;font-weight:800">'+n1+' × '+n2+' = ?</div><input id="mm2" style="font-size:22px;width:110px;padding:7px;text-align:center;border:2px solid #e5e5ea;border-radius:9px" placeholder="?"><button class="bs bb" style="font-size:13px;margin-top:5px" onclick="var v=parseInt(document.getElementById(\'mm2\').value);if(v==='+an3+'){baGScr+=2}else{baGScr=Math.max(0,baGScr-1)}document.getElementById(\'ba-g-score\').textContent=\'⏱\'+baGDur+\'s|\'+baGScr;nq3()">确认</button>'}nq3()}});
BA_GAMES.push({id:22,n:'数字排序',ic:'🔤',cat:'数学',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);function nq4(){if(!baGAct)return;const ns=[];for(let k=0;k<5;k++)ns.push(Math.floor(Math.random()*99)+1);const srt=[...ns].sort((a2,b2)=>a2-b2);a.innerHTML='<div style="font-size:12px;margin-bottom:4px">从小到大排列：</div><div style="display:flex;gap:5px;flex-wrap:wrap;justify-content:center">'+ns.map((n,i)=>'<button style="font-size:15px;padding:8px 10px;background:#f0f0ee;border:none;border-radius:9px;min-height:40px;cursor:pointer" id="ns'+i+'" onclick="var b=document.getElementById(\'ns'+i+'\');b.style.background=b.style.background===\'rgb(42,120,214)\'?\'#f0f0ee\':\'#2a78d6\';b.style.color=b.style.color===\'rgb(255,255,255)\'?\'#000\':\'#fff\'">'+n+'</button>').join('')+'</div><button class="bs bb" style="font-size:12px;margin-top:4px" onclick="var sl=[];for(var i=0;i<5;i++){var b=document.getElementById(\'ns\'+i);if(b&&b.style.background===\'rgb(42,120,214)\')sl.push(parseInt(b.textContent))}if(sl.length===5&&sl.every(function(v,i){return v==='+JSON.stringify(srt)+'[i]})){baGScr+=4}else if(sl.length===5){baGScr=Math.max(0,baGScr-2)}document.getElementById(\'ba-g-score\').textContent=\'⏱\'+baGDur+\'s|\'+baGScr;nq4()">✅提交</button>'}nq4()}});
BA_GAMES.push({id:23,n:'找质数',ic:'🔢',cat:'数学',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;flex-wrap:wrap;gap:6px;align-items:center;justify-content:center;padding:12px;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);const pl=[];for(let i=2;i<=50;i++){let ip=true;for(let j=2;j*j<=i;j++){if(i%j===0){ip=false;break}}pl.push({n:i,p:ip})}function nr5(){const qs=pl.sort(()=>Math.random()-.5).slice(0,12);a.innerHTML='';qs.forEach(q=>{const b=document.createElement('button');b.style.cssText='font-size:14px;padding:7px 10px;border-radius:9px;border:2px solid #e5e5ea;background:#fff;cursor:pointer;min-width:40px;min-height:40px';b.textContent=q.n;b.addEventListener('pointerdown',function(){if(!baGAct)return;if(q.p){b.style.background='#0ca30c';b.style.color='#fff';baGScr+=2}else{b.style.background='#e34948';b.style.color='#fff';baGScr=Math.max(0,baGScr-1)}b.disabled=true;b.style.opacity='.6';document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr;if(Array.from(a.children).every(c=>c.disabled))nr5()});a.appendChild(b)})}nr5()}});
BA_GAMES.push({id:24,n:'凑24点',ic:'🎯',cat:'数学',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);function nq5(){const ns=[];for(let i=0;i<4;i++)ns.push(Math.floor(Math.random()*9)+1);a.innerHTML='<div style="font-size:26px;font-weight:800;letter-spacing:6px">'+ns.join(' ')+'</div><div style="font-size:12px;color:var(--i3)">用+ - × ÷ 使结果=24</div><div style="display:flex;gap:6px"><button style="font-size:15px;padding:8px 16px;min-height:42px;background:#0ca30c;color:#fff;border:none;border-radius:9px;cursor:pointer" onclick="baGScr+=5;document.getElementById(\'ba-g-score\').textContent=\'⏱\'+baGDur+\'s|\'+baGScr;nq5()">✅ 做出来了</button><button style="font-size:15px;padding:8px 16px;min-height:42px;background:#e34948;color:#fff;border:none;border-radius:9px;cursor:pointer" onclick="nq5()">🔄 换一题</button></div>'}nq5()}});
// 25-28: Canvas Arcade
BA_GAMES.push({id:25,n:'贪吃蛇',ic:'🐍',cat:'休闲',t:BA_GAME_SEC,ini2:()=>baGCvC({t:600,ini:(c,w,h,d)=>{d.sk=[{x:10,y:10},{x:9,y:10},{x:8,y:10}];d.dr={x:1,y:0};d.fd={x:5,y:5};d.gs=16;d.cs=Math.floor(w/d.gs);d.rs=Math.floor(h/d.gs);d.tk=0},upd:(c,w,h,d)=>{d.tk++;if(d.tk%8!==0)return;const hd={x:d.sk[0].x+d.dr.x,y:d.sk[0].y+d.dr.y};if(hd.x<0||hd.x>=d.cs||hd.y<0||hd.y>=d.rs||d.sk.some(s=>s.x===hd.x&&s.y===hd.y)){gEnd(baGScr);return}d.sk.unshift(hd);if(hd.x===d.fd.x&&hd.y===d.fd.y){baGScr+=3;d.fd={x:Math.floor(Math.random()*d.cs),y:Math.floor(Math.random()*d.rs)};document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr}else{d.sk.pop()}c.fillStyle='#0ca30c';d.sk.forEach(s=>c.fillRect(s.x*d.gs,s.y*d.gs,d.gs-2,d.gs-2));c.fillStyle='#e34948';c.fillRect(d.fd.x*d.gs,d.fd.y*d.gs,d.gs-2,d.gs-2)},clk:(x,y,d)=>{const dx=x-d.sk[0].x*d.gs,dy=y-d.sk[0].y*d.gs;if(Math.abs(dx)>Math.abs(dy)){d.dr={x:dx>0?1:-1,y:0}}else{d.dr={x:0,y:dy>0?1:-1}}}})});
BA_GAMES.push({id:26,n:'弹球打砖',ic:'🏓',cat:'休闲',t:BA_GAME_SEC,ini2:()=>baGCvC({t:600,ini:(c,w,h,d)=>{d.pd={x:w/2-40,y:h-30,w:80,h:12};d.bl={x:w/2,y:h-50,r:6,vx:3,vy:-3};d.br=[];for(let r=0;r<5;r++)for(let cl=0;cl<8;cl++)d.br.push({x:cl*50+5,y:r*25+10,w:46,h:20,al:1});d.mx=w/2},upd:(c,w,h,d)=>{d.pd.x=d.mx-d.pd.w/2;d.pd.x=Math.max(0,Math.min(w-d.pd.w,d.pd.x));d.bl.x+=d.bl.vx;d.bl.y+=d.bl.vy;if(d.bl.x<=d.bl.r||d.bl.x>=w-d.bl.r)d.bl.vx*=-1;if(d.bl.y<=d.bl.r)d.bl.vy*=-1;if(d.bl.y>=h-30-d.bl.r&&d.bl.x>=d.pd.x&&d.bl.x<=d.pd.x+d.pd.w){d.bl.vy*=-1;d.bl.y=h-30-d.bl.r-1}if(d.bl.y>h){gEnd(baGScr);return}d.br.forEach(b=>{if(b.al&&d.bl.x>b.x&&d.bl.x<b.x+b.w&&d.bl.y>b.y&&d.bl.y<b.y+b.h){b.al=0;d.bl.vy*=-1;baGScr+=2;document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr}});if(d.br.every(b=>!b.al)){baGScr+=10;for(let r=0;r<5;r++)for(let cl=0;cl<8;cl++)d.br.push({x:cl*50+5,y:r*25+10,w:46,h:20,al:1})}c.fillStyle='#2a78d6';c.fillRect(d.pd.x,d.pd.y,d.pd.w,d.pd.h);c.fillStyle='#e34948';c.beginPath();c.arc(d.bl.x,d.bl.y,d.bl.r,0,Math.PI*2);c.fill();['#f66','#ff9500','#fd0','#0ca30c','#4a3aa7'].forEach((cl,r)=>{c.fillStyle=cl;d.br.filter(b=>b.al&&Math.floor(b.y/25)===r).forEach(b=>c.fillRect(b.x,b.y,b.w,b.h))})},clk:()=>{},mv:1})});
BA_GAMES.push({id:27,n:'小鸟飞行',ic:'🐤',cat:'休闲',t:BA_GAME_SEC,ini2:()=>baGCvC({t:600,ini:(c,w,h,d)=>{d.bd={x:60,y:h/2,vy:0,r:12};d.pp=[];d.fm=0},upd:(c,w,h,d)=>{if(!baGAct)return;d.fm++;d.bd.vy+=.4;d.bd.y+=d.bd.vy;if(d.bd.y<0||d.bd.y>h){gEnd(baGScr);return}if(d.fm%60===0){d.pp.push({x:w,gp:80+Math.random()*60,gy:60+Math.random()*(h-160)});if(d.pp.length>4)d.pp.shift()}d.pp.forEach(p=>{p.x-=3;if(d.bd.x+d.bd.r>p.x&&d.bd.x-d.bd.r<p.x+40){if(d.bd.y-d.bd.r<p.gy||d.bd.y+d.bd.r>p.gy+p.gp){gEnd(baGScr);return}}if(p.x<-40){baGScr+=2;var sc=document.getElementById('ba-g-score');if(sc)sc.textContent='⏱'+baGDur+'s|'+baGScr}});d.pp=d.pp.filter(p=>p.x>-60);c.fillStyle='#87CEEB';c.fillRect(0,0,w,h);c.fillStyle='#fd0';c.beginPath();c.arc(d.bd.x,d.bd.y,d.bd.r,0,Math.PI*2);c.fill();c.fillStyle='#0ca30c';d.pp.forEach(p=>{c.fillRect(p.x,0,40,p.gy);c.fillRect(p.x,p.gy+p.gp,40,h-p.gy-p.gp)})},clk:(x,y,d)=>{d.bd.vy=-6}})});
BA_GAMES.push({id:28,n:'躲避陨石',ic:'☄️',cat:'休闲',t:BA_GAME_SEC,ini2:()=>baGCvC({t:600,ini:(c,w,h,d)=>{d.sp={x:w/2,y:h-40,w:30,h:30};d.rk=[];d.mx=w/2},upd:(c,w,h,d)=>{d.sp.x=d.mx-d.sp.w/2;d.sp.x=Math.max(0,Math.min(w-d.sp.w,d.sp.x));if(Math.random()<.05)d.rk.push({x:Math.random()*w,y:-20,r:10+Math.random()*15});d.rk.forEach(r=>{r.y+=3;if(r.y>h+20){baGScr+=1;document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr}});d.rk=d.rk.filter(r=>r.y<h+40);for(const r of d.rk){if(Math.abs(d.sp.x+d.sp.w/2-r.x)<r.r+15&&Math.abs(d.sp.y+d.sp.h/2-r.y)<r.r+15){gEnd(baGScr);return}}c.fillStyle='#2a78d6';c.beginPath();c.moveTo(d.sp.x+d.sp.w/2,d.sp.y);c.lineTo(d.sp.x+d.sp.w,d.sp.y+d.sp.h);c.lineTo(d.sp.x,d.sp.y+d.sp.h);c.closePath();c.fill();c.fillStyle='#888';d.rk.forEach(r=>{c.beginPath();c.arc(r.x,r.y,r.r,0,Math.PI*2);c.fill()})},clk:()=>{},mv:1})});
// 29-36: Fun
BA_GAMES.push({id:29,n:'钓鱼达人',ic:'🎣',cat:'休闲',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:260px;position:relative;overflow:hidden;background:linear-gradient(180deg,#87CEEB 60%,#1a5276 60%);cursor:pointer';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);const f2=['🐟','🐠','🐡','🦈','🐋','🐙'];function sp2(){if(!baGAct)return;const f=document.createElement('div');f.style.cssText='position:absolute;font-size:26px;top:'+(40+Math.random()*40)+'%;left:-40px;transition:left '+(2+Math.random()*3)+'s linear;cursor:pointer;z-index:2';f.textContent=f2[Math.floor(Math.random()*f2.length)];const p2=f.textContent==='🦈'?5:f.textContent==='🐋'?4:f.textContent==='🐙'?3:1;f.addEventListener('pointerdown',function(e){e.preventDefault();if(!baGAct)return;baGScr+=p2;document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr;f.style.transform='scale(1.5)';f.style.opacity='0';setTimeout(()=>f.remove(),200)});a.appendChild(f);requestAnimationFrame(()=>{f.style.left=a.offsetWidth+'px'});setTimeout(()=>{if(f.parentNode)f.remove()},4000);baGData.ft2=setTimeout(sp2,800+Math.random()*1200)}sp2();baGData.cl=()=>{clearTimeout(baGData.ft2);while(a.firstChild)a.removeChild(a.firstChild)}}});
BA_GAMES.push({id:30,n:'幸运转盘',ic:'🎰',cat:'休闲',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);const pz=[1,2,3,5,8,10,1,2],em2=['⭐','🌟','💫','✨','🎯','💎','🔮','🎪'];a.innerHTML='<div id="wl" style="font-size:56px;transition:transform 2s cubic-bezier(.17,.67,.12,.99);display:inline-block">'+em2[0]+'</div><div style="font-size:11px;color:var(--i3)">点击转盘！</div>';a.style.cursor='pointer';a.addEventListener('pointerdown',function(){if(!baGAct)return;const w2=document.getElementById('wl');let ix=0;const iv=setInterval(()=>{ix=(ix+1)%pz.length;w2.textContent=em2[ix]},80);setTimeout(()=>{clearInterval(iv);const p2=pz[ix];baGScr+=p2;document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr;w2.style.transform='scale(1.3)';setTimeout(()=>w2.style.transform='scale(1)',300)},2000)})}});
BA_GAMES.push({id:31,n:'猜拳大战',ic:'✊',cat:'休闲',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);const op2=['✊','✋','✌️'];function rd2(){if(!baGAct)return;const ai=Math.floor(Math.random()*3);a.innerHTML='<div style="font-size:12px">你出什么？</div><div style="display:flex;gap:12px">'+op2.map((o,i)=>'<button style="font-size:30px;padding:12px 14px;background:#fff;border:2px solid #e5e5ea;border-radius:12px;cursor:pointer;min-height:54px;min-width:54px" onclick="var r;if('+i+'==='+ai+')r=0;else if(('+i+'===0&&'+ai+'===2)||('+i+'===1&&'+ai+'===0)||('+i+'===2&&'+ai+'===1))r=1;else r=-1;if(r===1)baGScr+=2;else if(r===-1)baGScr=Math.max(0,baGScr-1);document.getElementById(\'ba-g-score\').textContent=\'⏱\'+baGDur+\'s|\'+baGScr;rd2()">'+o+'</button>').join('')+'</div><div style="font-size:14px;margin-top:4px">🤖 '+op2[ai]+'</div>'}rd2()}});
BA_GAMES.push({id:32,n:'表情匹配',ic:'😊',cat:'休闲',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);const ps2=[['🐶','小狗'],['🐱','小猫'],['🐮','奶牛'],['🐷','小猪'],['🐸','青蛙'],['🦊','狐狸'],['🐻','熊'],['🐼','熊猫']];function nr6(){if(!baGAct)return;const p2=ps2[Math.floor(Math.random()*ps2.length)],cr=Math.random()>.5,lb=cr?p2[1]:ps2[Math.floor(Math.random()*ps2.length)][1];a.innerHTML='<div style="font-size:56px">'+p2[0]+'</div><div style="font-size:20px;font-weight:700">'+lb+'</div><div style="display:flex;gap:10px;margin-top:6px"><button style="font-size:13px;padding:8px 20px;background:#0ca30c;color:#fff;border:none;border-radius:10px;cursor:pointer;min-height:42px" onclick="if('+cr+'){baGScr+=1}else{baGScr=Math.max(0,baGScr-1)}nr6()">✅对</button><button style="font-size:13px;padding:8px 20px;background:#e34948;color:#fff;border:none;border-radius:10px;cursor:pointer;min-height:42px" onclick="if(!('+cr+')){baGScr+=1}else{baGScr=Math.max(0,baGScr-1)}nr6()">❌错</button></div>'}nr6()}});
BA_GAMES.push({id:33,n:'字母排序',ic:'🔡',cat:'休闲',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);function nr7(){const lt='ABCDEFGHIJKLMNOPQRSTUVWXYZ',ls=[];for(let k=0;k<6;k++)ls.push(lt[Math.floor(Math.random()*26)]);const sr=[...ls].sort();a.innerHTML='<div style="font-size:12px">按字母顺序：</div><div style="display:flex;gap:4px;flex-wrap:wrap;justify-content:center">'+ls.map((l,i)=>'<button style="font-size:18px;padding:7px 9px;background:#f0f0ee;border:none;border-radius:9px;min-height:40px;min-width:40px;cursor:pointer" id="al'+i+'" onclick="var b=document.getElementById(\'al'+i+'\');b.style.background=b.style.background===\'rgb(42,120,214)\'?\'#f0f0ee\':\'#2a78d6\';b.style.color=b.style.color===\'rgb(255,255,255)\'?\'#000\':\'#fff\'">'+l+'</button>').join('')+'</div><button class="bs bb" style="font-size:12px;margin-top:4px" onclick="var sl=[];for(var i=0;i<6;i++){var b=document.getElementById(\'al\'+i);if(b&&b.style.background===\'rgb(42,120,214)\')sl.push(b.textContent)}if(sl.length===6&&sl.every(function(v,i){return v===\''+sr.join('')+'\'[i]})){baGScr+=3}else if(sl.length===6){baGScr=Math.max(0,baGScr-1)}document.getElementById(\'ba-g-score\').textContent=\'⏱\'+baGDur+\'s|\'+baGScr;nr7()">✅提交</button>'}nr7()}});
BA_GAMES.push({id:34,n:'最强大脑',ic:'🧠',cat:'休闲',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;flex-wrap:wrap;gap:3px;align-items:center;justify-content:center;padding:8px;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);const cs7=['#e34948','#2a78d6','#0ca30c','#eda100','#eb6834','#4a3aa7'];function nr8(){const n2=12+Math.floor(Math.random()*9),bc2=cs7[Math.floor(Math.random()*cs7.length)];let di=-1;while(di<0||cs7[di]===bc2)di=Math.floor(Math.random()*cs7.length);const oi=Math.floor(Math.random()*n2);a.innerHTML='';for(let i=0;i<n2;i++){const d=document.createElement('div');d.style.cssText='width:32px;height:32px;border-radius:7px;background:'+(i===oi?cs7[di]:bc2)+';cursor:pointer;min-width:32px;min-height:32px';d.addEventListener('pointerdown',function(){if(!baGAct)return;if(i===oi){baGScr+=2}else{baGScr=Math.max(0,baGScr-1)}document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr;nr8()});a.appendChild(d)}}nr8()}});
BA_GAMES.push({id:35,n:'倒计时猜秒',ic:'⏱️',cat:'休闲',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px;background:#fafaf9;cursor:pointer';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);function nr9(){if(!baGAct)return;const tg=3+Math.floor(Math.random()*6);a.innerHTML='<div style="font-size:13px">在<b>'+tg+'</b>秒时点击！</div><div style="font-size:44px;font-weight:800" id="td2">0.0</div>';let st3=Date.now(),rn=true;baGData.ti=setInterval(()=>{if(!rn)return;document.getElementById('td2').textContent=((Date.now()-st3)/1000).toFixed(1)},50);a.addEventListener('pointerdown',function h2(){if(!baGAct||!rn)return;rn=false;clearInterval(baGData.ti);const elp=Math.abs((Date.now()-st3)/1000-tg);let pt2=elp<.3?5:elp<.7?3:elp<1.5?1:0;baGScr+=pt2;document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr;a.removeEventListener('pointerdown',h2);setTimeout(nr9,800)})}nr9();baGData.cl=()=>{clearInterval(baGData.ti)}}});
BA_GAMES.push({id:36,n:'数字大转盘',ic:'🎡',cat:'休闲',t:BA_GAME_SEC,ini2:()=>{const a=document.getElementById('ba-g-area');a.innerHTML='';a.style.cssText='min-height:240px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;background:#fafaf9';baGScr=0;baGAct=true;gT2(BA_GAME_SEC);const sg=[1,3,5,2,8,1,4,10,2,6,1,3];a.innerHTML='<div style="font-size:12px;margin-bottom:3px">点击旋转！</div><div style="position:relative;width:160px;height:160px"><svg viewBox="0 0 200 200" style="width:160px;height:160px;transition:transform 3s cubic-bezier(.17,.67,.12,.99)" id="sW"><circle cx="100" cy="100" r="95" fill="#fd0" stroke="#ccc" stroke-width="2"/>'+sg.map((s,i)=>{const a3=(i/sg.length)*360,a4=((i+1)/sg.length)*360,x1=100+90*Math.cos(a3*Math.PI/180),y1=100+90*Math.sin(a3*Math.PI/180),x2=100+90*Math.cos(a4*Math.PI/180),y2=100+90*Math.sin(a4*Math.PI/180);return'<path d="M100 100 L'+x1+' '+y1+' A90 90 0 0 1 '+x2+' '+y2+' Z" fill="hsl('+(i*30)+',70%,60%)" stroke="#fff" stroke-width="1"/><text x="'+(100+60*Math.cos((a3+a4)/2*Math.PI/180))+'" y="'+(100+60*Math.sin((a3+a4)/2*Math.PI/180))+'" text-anchor="middle" dy=".35em" font-size="11" fill="#fff" font-weight="700">'+s+'</text>'}).join('')+'<circle cx="100" cy="100" r="14" fill="#fff"/><polygon points="190,100 175,95 175,105" fill="#e34948"/></svg></div>';a.style.cursor='pointer';a.addEventListener('pointerdown',function(){if(!baGAct)return;const w2=document.getElementById('sW'),rt=720+Math.random()*1080;w2.style.transform='rotate('+rt+'deg)';const segA=360/sg.length,ix=Math.floor(((360-rt%360)%360)/segA);setTimeout(()=>{baGScr+=sg[ix%sg.length];document.getElementById('ba-g-score').textContent='⏱'+baGDur+'s|'+baGScr},3000)})}});


function baPickRandomGame(){
  if(!BA_GAMES.length) return null;
  return BA_GAMES[Math.floor(Math.random()*BA_GAMES.length)];
}

function baPrepareGame(g){
  document.getElementById("ba-g-title").textContent=(g.ic||"🎮")+" "+g.n;
  document.getElementById("ba-g-score").textContent="⏱"+BA_GAME_SEC+"s|0";
  document.getElementById("ba-g-foot").textContent="类别:"+(g.cat||"休闲");
  document.getElementById("ba-g-btn").textContent="🎮 开始";
  document.getElementById("ba-g-btn").onclick=baStartPreparedGame;
  document.getElementById("ba-game-modal").classList.add("on");
  baGData._g=g;
}

function baStartPreparedGame(){
  var a=document.getElementById("ba-g-area");
  a.innerHTML="";
  if(baGData.cl) try{ baGData.cl(); }catch(e){}
  clearInterval(baGInt); clearTimeout(baGTm);
  if(baGRaf) cancelAnimationFrame(baGRaf);
  baGAct=false;
  var g=baGData._g;
  baGData={ _g:g };
  baGScr=0; baGDur=g.t||BA_GAME_SEC;
  a.style.cssText="min-height:240px";
  g.ini2();
  document.getElementById("ba-g-btn").textContent="游戏中…";
  document.getElementById("ba-g-btn").onclick=function(){};
}

function baCloseGameModal(){
  baGAct=false;
  clearInterval(baGInt); clearTimeout(baGTm);
  if(baGRaf) cancelAnimationFrame(baGRaf);
  if(baGData.cl) try{ baGData.cl(); }catch(e){}
  baGData={};
  document.getElementById("ba-game-modal").classList.remove("on");
}
